version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./html:/var/www/html
      - ./html/logs:/var/www/html/logs

    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --max-connections=2000
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
